user = 'cold'
config_directory = '/home/' .. user .. '/.config/awesome'
terminal = "alacritty"
browser = "firefox"
files_manager = "thunar"
editor = "/usr/bin/nvim"
editor_cmd = terminal .. " -e " .. editor
modkey = "Mod4"
vscode = "/usr/bin/code"
